import type { PrismaClient } from '@prisma/client';
import { logger } from '../../../config/logger';
import type { AmassEventPublisher } from '../../../observability/domain/ports/event-bus';
import type { PullRequestGateway } from '../../domain/ports/pull-request-gateway';

export interface RemediationDeliveryInput {
  readonly scanId: string;
  readonly patchId: string;
}

export interface RemediationDeliveryResult {
  readonly patchId: string;
  readonly vulnerabilityId: string;
  readonly status: 'DELIVERED' | 'FAILED';
  readonly prNumber: number | null;
  readonly prUrl: string | null;
  readonly prBranch: string | null;
  readonly prCommitSha: string | null;
  readonly error: string | null;
}

export interface RemediationDeliveryDependencies {
  readonly prisma: PrismaClient;
  readonly gateway: PullRequestGateway;
  readonly events?: AmassEventPublisher;
}

export class RemediationDeliveryService {
  constructor(private readonly deps: RemediationDeliveryDependencies) {}

  async deliver(input: RemediationDeliveryInput): Promise<RemediationDeliveryResult> {
    const { scanId, patchId } = input;
    logger.info({ scanId, patchId }, 'remediation_delivery:start');

    // 1. Load Patch & Vulnerability from database
    const patch = await this.deps.prisma.patch.findUnique({
      where: { id: patchId },
      include: {
        vulnerability: {
          include: {
            scan: {
              include: {
                repositories: {
                  include: { repository: true },
                  take: 1,
                },
              },
            },
          },
        },
      },
    });

    if (!patch) {
      throw new Error(`Patch with ID ${patchId} not found`);
    }

    logger.info({ scanId, patchId, status: patch.status }, 'remediation_delivery:patch_loaded');

    // 2. Strict Gating: only APPROVED patches may enter delivery
    if (patch.status !== 'APPROVED') {
      const msg = `Delivery refused: patch ${patchId} status is ${patch.status}, expected APPROVED`;
      logger.warn({ scanId, patchId, status: patch.status }, msg);
      throw new Error(msg);
    }

    // 2b. Idempotency Guard: return existing delivery result if PR metadata already exists in DB
    if (patch.prNumber && patch.prUrl && patch.prBranch) {
      logger.info({ scanId, patchId, prNumber: patch.prNumber, prUrl: patch.prUrl }, 'remediation_delivery:already_delivered');
      return {
        patchId,
        vulnerabilityId: patch.vulnerabilityId,
        status: 'DELIVERED',
        prNumber: patch.prNumber,
        prUrl: patch.prUrl,
        prBranch: patch.prBranch,
        prCommitSha: patch.prCommitSha,
        error: null,
      };
    }

    if (!patch.filePath || !patch.diffContent) {
      const msg = `Patch ${patchId} has no file path or diff content to deliver`;
      logger.error({ scanId, patchId }, msg);
      throw new Error(msg);
    }

    const vulnerability = patch.vulnerability;
    const repoRecord = vulnerability?.scan?.repositories[0]?.repository;

    const repositoryUrl = repoRecord?.url ?? 'https://github.com/Mayuresh1004/owasp-vuln-lab.git';
    const baseBranch = repoRecord?.branch ?? 'main';
    const headBranch = `amass/remediation/${patchId}`;

    const title = `[AMASS] Fix ${vulnerability?.vulnType ?? vulnerability?.title ?? 'security issue'} in ${patch.filePath}`;
    const body = [
      `### 🛡️ Autonomous Security Remediation`,
      ``,
      `**Vulnerability:** ${vulnerability?.title ?? vulnerability?.vulnType ?? 'Security Vulnerability'} (${vulnerability?.cweId ?? 'CWE'})`,
      `**Severity:** ${vulnerability?.severity ?? 'HIGH'}`,
      `**Target File:** \`${patch.filePath}\``,
      `**Patch ID:** \`${patchId}\``,
      ``,
      `#### RAG Context & Explanation`,
      patch.explanation ?? 'Defensive parameterized code fix to eliminate vulnerability.',
      ``,
      `---`,
      `*This patch was generated by AMASS Engineer Agent and independently validated in a disposable Critic sandbox.*`,
    ].join('\n');

    try {
      // 3. Deliver via PullRequestGateway
      const result = await this.deps.gateway.createPullRequest({
        owner: '',
        repo: '',
        baseBranch,
        headBranch,
        title,
        body,
        filePath: patch.filePath,
        diffContent: patch.diffContent,
        patchId,
        cloneUrl: repositoryUrl,
      });

      // 4. Persist PR metadata on success (keep Patch.status = APPROVED)
      await this.deps.prisma.patch.update({
        where: { id: patchId },
        data: {
          prNumber: result.prNumber,
          prUrl: result.prUrl,
          prBranch: result.headBranch,
          prCommitSha: result.commitSha,
          prStatus: result.prStatus,
          prDeliveredAt: new Date(),
          prError: null,
        },
      });

      // Emit REMEDIATION_PR_CREATED event
      this.emit(scanId, {
        eventType: 'REMEDIATION_PR_CREATED',
        agentType: 'SYSTEM',
        phase: 'remediation',
        status: 'SUCCEEDED',
        message: `PR #${result.prNumber} created: ${result.prUrl}`,
        metadata: {
          patchId,
          vulnerabilityId: vulnerability?.id ?? undefined,
          prNumber: result.prNumber,
          prUrl: result.prUrl,
          prBranch: result.headBranch,
          prStatus: result.prStatus,
        },
      });

      logger.info({ scanId, patchId, prNumber: result.prNumber, prUrl: result.prUrl }, 'remediation_delivery:completed');

      return {
        patchId,
        vulnerabilityId: patch.vulnerabilityId,
        status: 'DELIVERED',
        prNumber: result.prNumber,
        prUrl: result.prUrl,
        prBranch: result.headBranch,
        prCommitSha: result.commitSha,
        error: null,
      };
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message.slice(0, 300) : String(err);
      logger.error({ scanId, patchId, error: errorMsg }, 'remediation_delivery:failed');

      // On failure: preserve Patch.status = APPROVED, populate prError, do NOT mark vulnerability PATCHED
      await this.deps.prisma.patch.update({
        where: { id: patchId },
        data: { prError: errorMsg },
      }).catch(() => undefined);

      this.emit(scanId, {
        eventType: 'REMEDIATION_DELIVERY_FAILED',
        agentType: 'SYSTEM',
        phase: 'remediation',
        level: 'ERROR',
        status: 'FAILED',
        message: `Remediation delivery failed: ${errorMsg}`,
        metadata: {
          patchId,
          vulnerabilityId: vulnerability?.id ?? undefined,
          error: errorMsg,
        },
      });

      return {
        patchId,
        vulnerabilityId: patch.vulnerabilityId,
        status: 'FAILED',
        prNumber: null,
        prUrl: null,
        prBranch: null,
        prCommitSha: null,
        error: errorMsg,
      };
    }
  }

  private emit(scanId: string, input: Omit<import('../../../observability/domain/ports/event-bus').AmassEventInput, 'scanId'>): void {
    if (!this.deps.events) return;
    try {
      this.deps.events.publish({ ...input, scanId });
    } catch (err) {
      logger.warn({ err }, 'remediation_delivery.events: publish ignored');
    }
  }
}
