/**
 * Runtime configuration value objects — how a repository becomes a running
 * application. Strategy resolution is deterministic and bounded: either the
 * repository ships its own Dockerfile (Mode 1) or one of a few supported
 * runtimes (Mode 2) is generated from a fixed template. Anything else is an
 * explicit UNSUPPORTED_RUNTIME result — never ad-hoc guesswork.
 */

export type RuntimeStrategyName = 'dockerfile' | 'python' | 'node';

export type RuntimeStrategy = 'DOCKERFILE' | 'PYTHON' | 'NODE' | 'UNSUPPORTED';

export interface BuildRecipe {
  /** Base image the generated strategy builds from (Mode 2). */
  readonly baseImage: string;
  /** Dockerfile RUN steps (Mode 2). */
  readonly installSteps: readonly string[];
}

export interface RuntimeConfig {
  readonly strategy: RuntimeStrategy;
  /** Mode 1: repository-provided Dockerfile (mutually exclusive with `python`/`node`). */
  readonly dockerfile?: { readonly path: string };
  /** Mode 2: generated recipe for a supported stack. */
  readonly recipe?: BuildRecipe;
  /** Container command that starts the application (image CMD or explicit). */
  readonly command: readonly string[];
  /** Port the application listens on inside the container. */
  readonly port: number;
  /** HTTP path probed during health checks. */
  readonly healthPath: string;
}

/** Bounded resource envelope applied to every runtime container. */
export interface ResourceLimits {
  readonly cpus: number;
  readonly memory: string;
  readonly pids: number;
}

/** Result of one health probe against a candidate target. */
export interface HealthProbeResult {
  readonly reachable: boolean;
  readonly latencyMs: number;
  readonly statusCode?: number;
  readonly detail?: string;
}

export const PYTHON_DEFAULT_PORT = 8000;
export const NODE_DEFAULT_PORT = 3000;
export const DOCKERFILE_DEFAULT_PORT = 8080;

export const DEFAULT_HEALTH_PATH = '/';

/** Max install steps generated by Mode 2 (bounded build surface). */
export const MAX_GENERATED_INSTALL_STEPS = 12;